<?php


namespace App\Api\Serializer;


class DeleteUserSerializer extends UserSerializer
{

    public function getDefaultAttributes($model)
    {
        $attributes = parent::getDefaultAttributes($model); // TODO: Change the autogenerated stub

        return $attributes + [
            'error' => $model->error
            ];

    }
}
