<?php


namespace App\Api\Serializer;


class InfoSerializer extends UserSerializer
{

    public function getDefaultAttributes($model)
    {
//        $attributes = parent::getDefaultAttributes($model); // TODO: Change the autogenerated stub

        return [
            'id' => $model->id,
            'succeed' => (bool)$model->succeed,
            'error' => $model->error
            ];

    }
}
