CREATE TABLE `pay_orders` (
  `order_id` varchar(51) NOT NULL COMMENT '内部订单编号',
  `user_id` int(11) NOT NULL COMMENT '用户ID',
  `user_openid` varchar(34) NOT NULL COMMENT '用户的openid',
  `user_ip` varchar(50) NOT NULL COMMENT '用户的支付设备的IP地址',
  `pdt_type` int(11) NOT NULL COMMENT '支付的产品的类型（或类别）',
  `pdt_id` int(11) NOT NULL COMMENT '支付的产品的ID',
  `pdt_desc` varchar(50) NOT NULL COMMENT '支付的产品的说明（支付说明）',
  `total_fee` int(11) NOT NULL COMMENT '支付的金额',
  `pay_platform` enum('1','2','3','4','5','6','7','8','9','10') NOT NULL COMMENT '支付工具平台：1，微信支付；2，支付宝支付',
  `pay_sense` enum('1','2','3','4','5','6','7','8','9','10') NOT NULL COMMENT '支付的场景：1，PC扫码支付；2，手机H5支付；3，微信内部支付',
  `pay_status` varchar(15) NOT NULL COMMENT '订单的状态',
  `pay_order_id` varchar(150) NOT NULL COMMENT '支付平台的支付订单ID',
  `time_start` datetime NOT NULL COMMENT '订单创建时间',
  `time_expire` datetime NOT NULL COMMENT '订单失效时间',
  `err_time` datetime DEFAULT NULL COMMENT '订单异常时间',
  `err_code` varchar(15) DEFAULT NULL COMMENT '订单异常码',
  `err_code_desc` varchar(200) DEFAULT NULL COMMENT '订单异常消息',
  PRIMARY KEY (`order_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_product` (`pdt_type`,`pdt_id`),
  KEY `idx_user_prod` (`user_id`,`pdt_type`,`pdt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
